name: Svelte CI/CD - Self Hosted SSR

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm run build

  deploy:
    needs: build
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - name: Start Application
      run: pm2 start index.js
